# Generated by Django 3.0.7 on 2020-08-01 13:26

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
             field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='store.Brand'),
        ),
    ]
